name: Check Turtle Files

on:
    push:

jobs:
  checkttl:
    name: Checks Turtle Files
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Python Packages
        run: pip install -r requirments.txt
      - name: run check script
        run: python scripts/well_formed_check.py