name: Check Turtle Files

on:
    push:

jobs:
  checkttl:
    name: Checks Turtle Files
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: run check script
        run: ./scripts/well_formed_check.py
